### ISSUE TITLE
Bizarre finding

### ISSUE THREAD

**Issue by garrison** [zenhack/ekam-nix#2]
From a checkout of this repository, run:
```
$ nix-shell
$ ./builder.sh
```
and the build fails.  but then run:
```
$ cd ekam
$ make
```
and the build succeeds.  (For some reason it does not work if I do these steps in `/tmp`, however, so I recommend trying somewhere in the home directory tree.)

I also reproduced in Docker to make sure it is not pulling in some headers from elsewhere on my system:

```
FROM nixos/nix:latest
RUN nix-env -i git
RUN git clone https://github.com/zenhack/ekam-nix.git
WORKDIR /ekam-nix
RUN nix-shell --run ./builder.sh || echo build failed
RUN nix-shell --run "cd ekam && make"
```

I can add the flag `--pure` right after each `nix-shell` and it works still.

**Comment by garrison** [comment]
I suspect there might be some environment variable set by `$stdenv/setup` that is causing the build to fail.  I can't think of anything else that makes sense.  (And I'm a bit surprised that the build succeeds without the environment being set up as nix expects.)

**Comment by garrison** [comment]
I guess this is all not very surprising following the report at https://github.com/NixOS/nixpkgs/issues/79204#issuecomment-841902887

`PATH` does seem like the most obvious culprit.

**Comment by zenhack** [comment]
> For some reason it does not work if I do these steps in /tmp, however, so I recommend trying somewhere in the home directory tree.

Aha! `nix-build` does its builds in `/tmp`, so that's probably the culprit. So the next quesstion is why does it fail in /tmp?

...and I was able to reproduce the failure outside of nix, by just cloning ekam and attempting to build it in /tmp. So I'll open an issue for ekam.

**Comment by zenhack** [comment]
I opened https://github.com/capnproto/ekam/issues/57. Going to close this, thanks for helping.

**Comment by garrison** [comment]
Great!
