### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by zenhack** [zenhack/ekam-nix#3]
Opening an actual issue, so there's somewhere to centralize the discussion around getting this to build.

After capnproto/ekam#59 was merged, I updated the version used here, but got the same error... so we're not out of the woods yet. I haven't sat down to try to debug further though.

cc: @garrison

**Comment by garrison** [comment]
I managed to get a tentative working build in #4.

**Comment by zenhack** [comment]
Merged the PR, closing.

I did a bit of digging and came up with a clearer explanation of why unsetting the variable is necessary; see comments in f18fd808a3d4a797d0ab887931b13f39f023048d
